stages:
  - build-img

build-img:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build-img
  script: |
    echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG 
    --label "org.opencontainers.image.revision"="$CI_COMMIT_SHA" --label "org.opencontainers.image.source"="$CI_REPOSITORY_URL"  
    --label "org.opencontainers.image.created"="$(date -I)" --single-snapshot --snapshotMode=time
  only:
    - tags


